apiVersion: v1
kind: Service
metadata:
  name: {{ include "database.fullname" . }}
  labels:
    {{- include "database.labels" . | nindent 4 }}
spec:
  ports:
    - port: 3306
  selector:
    {{- include "database.selectorLabels" . | nindent 4 }}
